FROM node:lts-alpine as build_image

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm ci

COPY . .

RUN npx tsc --rootDir ./src --outDir ./dist -p tsconfig.build.json

FROM node:lts-alpine

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm ci --omit=dev

COPY --from=build_image /usr/src/app/dist ./dist