FROM node:lts-alpine AS build-image

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm ci

COPY . .

RUN npx tsc --rootDir ./src --outDir ./dist -p tsconfig.build.json

FROM node:lts-alpine

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm ci --omit=dev

COPY private.pem ./
COPY public.pem ./

COPY --from=build-image /usr/src/app/dist ./dist

CMD [ "node", "/usr/src/app/dist/index.js" ]